[package]
name = "xchdev-db"
version = "0.1.0"
edition = "2021"

[dependencies]
xchdev-types = { workspace = true }
chia = { workspace = true }
rocksdb = { workspace = true }
anyhow = { workspace = true }
num_cpus = { workspace = true }
ciborium = { workspace = true }
serde = { workspace = true }
